### ISSUE TITLE
Not working on dynamically added image source

### ISSUE THREAD

**Issue by kidach** [jackmoore/wheelzoom#11]
I populate image source with image path i got from ajax.
Something like 
$('#image').attr('src', resultFromAjax);

Am i doing something wrong? :)

**Comment by provolot** [comment]
Not sure if this helps, but adding 'var' to the main declaration on line 20 fixed a 
"Uncaught TypeError: object is not a function" error for me:
20: *var* main = function(img, options){

**Comment by gelevanog** [comment]
You can try to use imagesLoaded for that - http://imagesloaded.desandro.com/
