### ISSUE TITLE
Image shifts during zoom if page is scrolled down

### ISSUE THREAD

**Issue by aaugustin** [jackmoore/wheelzoom#17]
If you open your demo page and use the mouse wheel on the image, the point under the cursor doesn't move.

If you scroll the whole page down a bit and then use the mouse wheel on the image, the point under the cursor moves.

The more you scroll the page, the more dramatic the effect.

Latest Firefox, OS X.

**Comment by aaugustin** [comment]
This is not reproducible on Safari or Chrome.

**Comment by aaugustin** [comment]
Using `window.scrollX/Y` instead of `document.body.scrollLeft/Top` seems to fix it.

**Comment by jackmoore** [comment]
Whoops, thanks!

**Comment by jackmoore** [comment]
I appreciate all the tickets, alway surprised when someone finds a use for this.

**Comment by aaugustin** [comment]
Thank you very much for the library and the quick fixes!
