### ISSUE TITLE
default zoom value is not modified !

### ISSUE THREAD

**Issue by stoufa** [jackmoore/wheelzoom#20]
This is the code I used :
`<!doctype html>
<html>
	<head>
		<style>
			img {
			    width: 49%;
			    border: 1px solid black;
			}
			img.default {
			    float: left;
			}
			img.modified {
			    float: right;
			}
		</style>
	</head>
	<body>
		<img src="img/wheelzoomTest.png" class="default" title="default">
		<img src="img/wheelzoomTest.png" class="modified" title="modified">
		<script src="js/wheelzoom.js"></script>
		<script>
			wheelzoom(document.querySelectorAll('img.default'), {zoom:0.1});
			wheelzoom(document.querySelectorAll('img.modified'), {zoom:0.01});
		</script>
	</body>
</html>`
> There is no difference in zoom percent in both images !
![image](https://cloud.githubusercontent.com/assets/11628585/17619904/c5053b06-6088-11e6-8ad9-7449c9553ee6.png)

**Comment by jackmoore** [comment]
The zoom setting determines how much the image size changes for each time the scroll event fires.

**Comment by stoufa** [comment]
Yes I know ! I used two different zoom settings in the images and yet I get the same result ! ( for the same number of scrolls in both images of course ! )
So, I think that the value is not changed ! However, I only feel the difference when I modify the default value in wheelzoom.js !
![image](https://cloud.githubusercontent.com/assets/11628585/17629664/c5f7728a-60bb-11e6-9cc3-37b7e45fb0ae.png)

**Comment by jackmoore** [comment]
Sorry, I cannot reproduce the issue.

**Comment by stoufa** [comment]
No problem, changing the default value in wheelzoom.js is a sufficient solution for now :)
