### ISSUE TITLE
Problem in modal box

### ISSUE THREAD

**Issue by sudinem** [jackmoore/wheelzoom#22]
When I add the wheel zoom in dynamic content as image within modal box, the image is already in zoomed state and I could not zoom in and zoom out the image. Nothing happens to the image. How to resolve this issue ?

**Comment by juanmas07** [comment]
the same here, not working inside bootstrap modals

**Comment by MarlonWilkes** [comment]
+1

**Comment by Cepulis** [comment]
+1

**Comment by mldxpt** [comment]
It's working for me by adding a timeout :
setTimeout(function(){ wheelzoom(document.querySelectorAll('img.zoomable')); }, 500);

**Comment by Timothy0** [comment]
Used "visibility: hidden;" instead of "display none;" to hide the images/modal and it now works for me.

**Comment by Cepulis** [comment]
Hey, I came up with a workaround, setting timeout seems to solve this issue.

`setTimeout(function(){ wheelzoom(document.querySelectorAll("img.zoomable")); }, 500);`
