### ISSUE TITLE
What files need to be imported after npm install to run this library on angular 5, and can i apply this on canvas?

### ISSUE THREAD

**Issue by PARULAGRAWALdei** [jackmoore/wheelzoom#34]
Hey, I want to use this zooming mode on my canvas image. I have installed your npm library, but don't know what files need to be imported to make it run. And i wan to do this zooming on canvas, so how it can be done? Let me know what you think.

**Comment by jackmoore** [comment]
Sorry, this is just for img elements and wouldn't work with canvas.
