### ISSUE TITLE
Zooming Issue with Specify CameraModel Image

### ISSUE THREAD

**Issue by vijaymadhavan** [jackmoore/wheelzoom#44]
Hi,
facing issue with Sensefly Camera model images,
May I know why it's happening?
[SenseflyIMage](https://cdn-workspace.s3.ap-south-1.amazonaws.com/images/1.JPG)

**Comment by jackmoore** [comment]
Works fine for me:
https://codepen.io/jacklmoore/pen/MWeqJXz
