### ISSUE TITLE
add PinchToZoom event

### ISSUE THREAD

**Issue by babeuloula** [jackmoore/wheelzoom#9]
Hello, 
I use your code with a iPad and i can't zoom with my fingers. Do you have a solution ?
Thanks

**Comment by brandflugan** [comment]
Jack seems to be very inactive lately regarding his own stuff on github, I would be surprised if he ever add new functions to it. A pinch zoom would be really great with this, even better if it was added to the jquery zoom.

**Comment by gchokeen** [comment]
+1 for this

**Comment by meeximum** [comment]
+1

**Comment by RadiksMan** [comment]
+1

**Comment by MickL** [comment]
Hey guys, commenting "+1" spams the issue tracker. Instead you might add your thumbs up to the issue itself.

Anyway: This module can be forked by any of you guys and add a pinch gesture. Also currently it cant be imported by modern JS/TS.
